# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: buildmeister 3.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "buildmeister"
  s.version = "3.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Leigh Caplan"]
  s.date = "2013-10-16"
  s.description = "Dead simple tools for managing Lighthouse and Git deployment workflow"
  s.email = "lcaplan@onehub.com"
  s.executables = ["buildmeister", "git_cleanup"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "History.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/buildmeister",
    "bin/git_cleanup",
    "lib/buildmeister.rb",
    "lib/buildmeister/base.rb",
    "lib/buildmeister/bin.rb",
    "lib/buildmeister/core_ext.rb",
    "lib/buildmeister/finder.rb",
    "lib/buildmeister/git_utils.rb",
    "lib/buildmeister/json_tools.rb",
    "lib/buildmeister/json_utils.rb",
    "lib/buildmeister/notifier.rb",
    "lib/buildmeister/project.rb",
    "lib/buildmeister/string_utils.rb",
    "lib/git_cleanup.rb",
    "lib/lighthouse/account.rb",
    "lib/lighthouse/bin.rb",
    "lib/lighthouse/project.rb",
    "lib/lighthouse/ticket.rb",
    "spec/buildmeister/base_spec.rb",
    "spec/buildmeister/bin_spec.rb",
    "spec/lighthouse/account_spec.rb",
    "spec/lighthouse/bin_spec.rb",
    "spec/lighthouse/project_spec.rb",
    "spec/lighthouse/ticket_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/support/bins.json",
    "spec/support/projects.json",
    "spec/support/tickets.json"
  ]
  s.homepage = "http://github.com/onehub/buildmeister"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.8"
  s.summary = "Dead simple tools for managing Lighthouse and Git deployment workflow"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<rest-client>, ["~> 1.6.7"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rest-client>, ["~> 1.6.7"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rest-client>, ["~> 1.6.7"])
  end
end

