# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{buildmeister}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Leigh Caplan"]
  s.date = %q{2009-12-10}
  s.description = %q{Dead simple tools for managing Lighthouse and Git deployment workflow}
  s.email = %q{lcaplan@onehub.com}
  s.executables = ["buildmeister", "git_cleanup"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
     "Manifest.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/buildmeister",
     "bin/git_cleanup",
     "lib/buildmeister.rb",
     "lib/buildmeister/base.rb",
     "lib/buildmeister/bin.rb",
     "lib/buildmeister/finder.rb",
     "lib/buildmeister/git_utils.rb",
     "lib/buildmeister/notifier.rb",
     "lib/buildmeister/project.rb",
     "lib/buildmeister/string_utils.rb",
     "lib/git_cleanup.rb",
     "spec/buildmeister/base_spec.rb",
     "spec/buildmeister/bin_spec.rb",
     "spec/buildmeister/project_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/onehub/buildmeister}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Dead simple tools for managing Lighthouse and Git deployment workflow}
  s.test_files = [
    "spec/buildmeister/base_spec.rb",
     "spec/buildmeister/bin_spec.rb",
     "spec/buildmeister/project_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

