token: your_token
account: your-account

projects:
  - name: Macchiato
    bins:
      - Ready
      - Staged
      - Verified
      - Ready (Experimental)
      - Staged (Experimental)
      
  - name: Espresso
    bins:
      - Ready
      - Staged
      - Verified

notification_interval: 3