#!/usr/bin/env ruby

require  File.expand_path(File.dirname(__FILE__) + "/../lib/buildmeister")
require 'activesupport'

puts "Starting up BuildMeister..."

  bm    = Buildmeister.new('Macchiato')

while true do  
  title = "BuildMeister: #{Time.now.strftime("%m/%d %I:%M %p")}"
  body  = <<eos
Staging
---------
Ready: #{bm.ready.tickets_count}
Staged: #{bm.staged.tickets_count}
Verified: #{bm.verified.tickets_count}

Master
---------
Ready: #{bm.ready_experimental.tickets_count}
Staged: #{bm.staged_experimental.tickets_count}
eos

  puts "Updated notification at #{Time.now.strftime("%m/%d %I:%M %p")}"
  
  if bm.changed?
    `growlnotify -s -n "Lighthouse" -a "Lighthouse" -d 'buildmeister' -t "#{title}" -m "#{body}"`    
  end
  
  sleep 5.minutes.to_i
  
  bm.reload_info
end